### ISSUE TITLE
IdleMode: sometimes isn't hidden with no any activity

### ISSUE THREAD

**Issue by sslebedev** [Skamer/Eska-Tracker#18]
-

**Comment by Skamer** [comment]
In the lastest release, the idle mode has been reworked. I decided to remove the control of the activity for all frames except trackers and blocks. The modules can still control it from blocks they use. 

Now, let's talk about when a tracker is considered as idle or not. 

The tracker is still considered active when:
-  you are in dungeon, mythic +, worldquest zone,  bonus objectives zone and scenario. 
-  you have tracked an achievement. 

For quests, the behavior is different. The tracker will still be considered active if there is a quest on the map where you are, otherwise the tracker became inactive.

Don't hesitate to let your feedback about when the tracker is considered as inactive.

**Comment by dougarley** [comment]
> For quests, the behavior is different. The tracker will still be considered active if there is a quest on the map where you are, otherwise the tracker became inactive.

Is this regarding location based on proximity to quest objectives or zone? In my testing it currently seems to be by zone, so I'm just trying to confirm that is intended. 

Options I would personally like to see regarding idle mode:

1. The ability to remain idle until progress updates.
2. Graceful fading. Something like on inactive fade to X opacity over Y ms, on active fade back to X opacity over Y ms.

**Comment by Skamer** [comment]
It's by zone. But i planned to add an option where you can choice:
- By zone 
- By zone + proximity 

> If so: The ability to limit quests to the current zone (which I love, btw), and idle/active mode seem to serve a similar purpose.

This is the case if you have only the QuestBlock for a tracker.

> The ability to remain idle until progress updates.

The idle mode is experimental and new, so i want to wait before to try to make things more complex. 

> Graceful fading. Something like on inactive fade to X opacity over Y ms, on active fade back to X opacity over Y ms.

Interesting. I have no ETA to give, but this shouldn't take too long.
