### ISSUE TITLE
World Quests do not untrack

### ISSUE THREAD

**Issue by AussieEevee** [Skamer/Eska-Tracker#24]
**Describe the bug**
I was in darkshore, and did one world quest, I clicked on another to look at it but chose not to do it and hearthed to Draenor to do some quests there... but the Darkshore world quest is still showing on my tracker and won't let me untrack it.

**Do you have an error log of what happened?**
No error is generated.

**To Reproduce**
Click on a world quest on the map then leave the area.

**Expected behavior**
I expect world quests to be removed from the tracker when they are no longer relevant, such as when I'm on an entirely different planet.

**Screenshots**

**What is the version of EskaTracker you use ?**
1.0.22

**What are the versions of PLoop and Scorpio you use ?**
(You can known that in opening the EskaTracker options)
- PLoop: 224
- Scorpio: 24

**Additional context**

**Comment by b3n9ti** [comment]
+1
World quests indeed can not be untracked even when you leave the area.

**Comment by ZachieBlade** [comment]
This also happens with Bonus Objectives. I have one from Draenor that will not go away.

**Comment by Skamer** [comment]
This answer concerns also #22 
When the issue occurs, can you give me the following information.
- Right click to open the context menu -> [Debug] Info -> give me the value of 'isTracked' printed in the chat.

### What's happen ? 
Blizzard supertracks the Darkshore world quests, which is something i have not expected because it's not the case for Broken Isles  world quests. I need to update the module to include this new case, i'll try to do that quickly as possible.

### Temporary fix. 
In waiting, there is something you can do to avoid the issue, it's to type this command:
`/run EKT.Settings:Set("show-tracked-world-quests", false)`

To explain this setting, this ask if you want the world quests which are tracked from Blizzard Map Frame and the supertrack must be shown. The world quests tracked are displayed even if you are not in their zone. It's the reason of why i ask you the value of '**isTracked**'. 

This setting is currently by default to true, which isn't intended. I'll set to false in the next build, in addition to add the options about it.

**Comment by Skamer** [comment]
@ZachieBlade  Can you make a screenshot of all informations printed in chat instead of only 'isTracked' ?

**Comment by AussieEevee** [comment]
This and #22 are happening in Azsuna, during a Legion invasion.

I can't click the one I've already completed, as the current one is drawing on top of it.

**Comment by Skamer** [comment]
> This and #22 are happening in Azsuna, during a Legion invasion.
>
>I can't click the one I've already completed to get debug information, as the current one is drawing on top of it.

You still encounter the issue with the version **1.0.19** of EskaTracker_Objectives ?

**Comment by AussieEevee** [comment]
> You still encounter the issue with the version 1.0.19 of EskaTracker_Objectives ?"

Doing invasion quests in Val'Sharah right now. Hasn't happened yet.
