### ISSUE TITLE
Old quests remain tracked even when removed from the quest log

### ISSUE THREAD

**Issue by ZachieBlade** [Skamer/Eska-Tracker#25]
**Describe the bug**
This is very strange.. so I finished all of the quests I had, and they all disappeared from my quest log. I picked up some new ones, they did not track, so I manually tracked them. They all appeared in my sidebar.. along with some old quests that I do not have anymore, but they show as having the objectives completed. I'll include screenshots.

**Do you have an error log of what happened?**
No error is generated.

**To Reproduce**
All I did was:
- Turn in quests
- Accept new quests
- Track the new quests.

**Expected behavior**
I expect it to only show quests I have. 

**Screenshots**
https://cdn.discordapp.com/attachments/405983245398966273/474820331312513035/WoWScrnShot_080318_160622.jpg

**What is the version of EskaTracker you use ?**
1.0.23-beta
1.0.18-beta (Objectives)

**What are the versions of PLoop and Scorpio you use ?**
(You can known that in opening the EskaTracker options)
- PLoop: 224
- Scorpio: 024

**Additional context**
The completed quests go away when I /reloadui.

**Comment by ZachieBlade** [comment]
This also might be related, so I won't do a second report, but I've noticed that sometimes quests won't update on the sidebar. This happens for WQs as well as regular quests. 

https://media.discordapp.net/attachments/405983245398966273/474820304191881236/WoWScrnShot_080318_155812.jpg?width=1202&height=677

**Comment by Skamer** [comment]
Your issue seems similar to #10 .  The case you encountered is when your quests have disappeared without triggered the expected event the addon needs to remove correctly the quest from tracker.  

In the 1.0.18-beta (Objectives), i prevented the quests to pull no valid informations to avoid empty line but it's not enough.  

I'll try a fix to remove the quests which disappeared. When the addon will update a quest while the information pulled aren't valid, this will remove the quest instead to prevent and keep it. This should fix the issue.

**Comment by Skamer** [comment]
I close it. The quests removed from quest log should now be correctly removed.

**Comment by ZachieBlade** [comment]
Reopening.

Had it happen tonight, however as soon as I clicked it from the tracker it went away.
