### ISSUE TITLE
BFA tracked quests are not being shown on login

### ISSUE THREAD

**Issue by AussieEevee** [Skamer/Eska-Tracker#34]
**Describe the bug**
Tracked quests are not being shown on login

**To Reproduce**
Have some quests tracked in the new zones, and exit the game then log back in. The game considers them tracked, but Eska does not. You have to untrack them and retrack them.

**Expected behavior**
I expect tracked quests to always show on the tracker

**What is the version of EskaTracker you use ?**
1.0.28

**What are the versions of PLoop and Scorpio you use ?**
(You can known that in opening the EskaTracker options)
- PLoop: 224
- Scorpio: 24

**Additional context**

**Comment by Skamer** [comment]
During my leveling, i encounter the same problem two to three time in a row then disappeared.  It very hard to fix the issue, because i couldn't reproduce it with a way reliable, not allowing me to gather information about how this happens. 

My current thought at this issues is this is caused by the Blizzard server. Let's me explain why:
- After a loading, EskaTracker will ask to game client if every quests is watched (tracked) or not. If yes, it adds the quest in the Quest Block, otherwise does nothing.
- I have some doubt about Blizzard server (surely caused by lag) to give the correct value if the quest has been watched or not, so preventing the addon to ask the quest.

Have you still encounter the issue now ?

I think i'll ask a new slash command to ask the addon to reload the quests.

**Comment by AussieEevee** [comment]
I am still having the problem, but it's random. Sometimes it works, sometimes it doesn't.

Is it possible to delay the loading of the quests by... Let's say 10 seconds... to account for lag and this information possibly not being available from the server immediately?

**Comment by Skamer** [comment]
It's possible. Can you test adding a delay will fix the issue ?

#### Step 1: Open the file 'EskaTracker_Objectives/Modules/Quests.lua', then go to the function (~line 110) 
```lua
__Async__()
__SystemEvent__()
function PLAYER_ENTERING_WORLD(initialLogin, reloadingUI)
  if initialLogin then
    -- If it's the first login, we need to wait 'QUEST_LOG_UPDATE' is fired to
    -- get valid informations about quests.
    Wait("QUEST_LOG_UPDATE")
  end

  _M:LoadQuests()

  UPDATE_BLOCK_VISIBILITY()
  _M:UpdateDistance()
end

```

####  Step 2: Add the delay 

After : 
```lua
Wait("QUEST_LOG_UPDATE")
```
Put:
```lua
Delay(10) -- delay 10s the loading
```

**Comment by AussieEevee** [comment]
I've done that and so far it seems to have helped. I'll let you know after I've been using that change for a while

**Comment by Skamer** [comment]
Thank you for having testing that. I've added the delay (5s) in the lastest alpha build.  
If you aren't happy with this delay, you can edit it by this way:
`/run EKT.Settings:Set("quests-loading-delay", 5)`
