### ISSUE TITLE
Tracker is completely blank since the update

### ISSUE THREAD

**Issue by HelenKellah** [Skamer/Eska-Tracker#63]
**Describe the bug**
Cannot track quests.  Border of EQT is visible but inside is completely blank.  Untracking and retracking quests does not help.

How it used to look:
![wowpurpleui](https://user-images.githubusercontent.com/46092607/50387216-48ba3e80-06c5-11e9-8413-61d10d49c086.jpg)

How it looks now
![wowscrnshot_122318_151348](https://user-images.githubusercontent.com/46092607/50387222-64bde000-06c5-11e9-8980-95a1925ae273.jpg)

**What is the version of EskaTracker you use ?**
1.1.8-release

**What are the versions of PLoop and Scorpio you use ?**
(You can known that in opening the EskaTracker options)
- PLoop: v230
- Scorpio: v025

**Additional context**
Please help I love this addon

**Comment by Skamer** [comment]
Yesterday, i was notified by the Scorpio author as there was recently a new update with some changes, but i haven't had the time for checking that in-game and updating the addon if needed until now. 

Indeed, EskaTracker doesn't work well with the latest version of Scorpio. **For the moment, the temporary answer to this issue is to rollback your Scorpio version to v024.** 

I'll pin this issue and make a note about that on the project description. Thanks for reporting it and sorry for disturbance.

**Comment by HelenKellah** [comment]
Thank you so much!
