### ISSUE TITLE
Problems with blizzard quest tracker

### ISSUE THREAD

**Issue by FaileDestiny** [Skamer/Eska-Tracker#83]
So I've been using your add on for a few years actually, thank you for your hard work.  A couple of things though with the 9.0 prepatch I've been having an issue with the blizzard quest tracker popping up even when i have the replace entirely option clicked on, all i have to do is go and turn it & back on but a bit repetitive.  I did just download Elvui so it might be something on their side, but can't see any options that deal with the quest tracker other then their auto-hide option, which I did test but still popped up with it toggled in both direcitons.

The other thing is do you know of any guides to your addon or any other, working on a new set up and i want the tracking blocks to hide when they are empty, so far I've been setting up one for keystones, world quests and then my normal quest & achievement tracker.  Which I would figure would be under the display rules, but theres no presets, or conditionals and i just dont know where to find them any clues where to look would be appreciated.

Thanks again =0)

**Comment by Skamer** [comment]
I use also ElvUI but i don't encounter the issue you have concerning the Blizzard quest tracker, so i don't know why this happens.

For displaying rules,  i have noticed there was an issue so i have just pushed a fix at this purpose. The problem was the options was broken due LUA errors i have forgotten to fix when i updated the addon for Shadowlands.

I had also written something a long time ago about displaying rules in the wiki is still relevant, [you can find here](https://github.com/Skamer/Eska-Tracker/wiki/Migration-guide-:-from-Eska-Quest-Tracker-to-EskaTracker#displaying-rules). This should be a good start for understand how this works. 

For your case with the quests and achievements, you can do something like that:
![image](https://user-images.githubusercontent.com/849450/97515387-3aa86980-1991-11eb-84ab-626063deb9a7.png)

If you have others questions, don't hesitate to ask here.

**Comment by FaileDestiny** [comment]
Thank you for the super quick response & that'll help me out alot =0)

**Comment by FaileDestiny** [comment]
So the rules themselves won't work for my situation as I always have quests being tracked (bad habit I know).  However, I was looking at the Status function and think that'll be my best bet.  However, I can't put any code in the text box.

**Comment by Skamer** [comment]
Indeed, i forgot to include a change in a file. I have repushed a new version (1.5.3c)

**Comment by FaileDestiny** [comment]
thanks that got it updated =0)
